import type { AcceptedPlugin } from 'postcss'
import { transformPxP } from '@lemonneko/pxp-transformer'

// FIXME: code generated by @apply won't be transpiled to `calc`
export function customUnitPxp(
  variableName: string,
  defaultValue: string,
): AcceptedPlugin {
  return {
    postcssPlugin: 'custom-unit-pxp',
    Declaration: (declaration) => {
      if (!declaration.value.includes('pxp'))
        return

      declaration.value = transformPxP(declaration.value, variableName, defaultValue)
    },
  }
}
